regex:
  email: !ruby/regexp /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
degit:
  length_name: 30
  length_email: 50
  length_6: 6
  min_books: 0
page:
  limit_items: 8
authors:
  per_page: 10
per_page: 10
category:
  max: 50
validate:
  email:
    length:
      max: 255
    regex: !ruby/regexp /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  name:
    length:
      max: 50
model:
  image_type: <%= %w(image/jpeg image/gif image/png) %>
book:
  title_max: 50
  year: 1
  amount: 1
  rate_min: 0
  rate_max: 5
publisher_search: <%= %w(name email address) %>
author_search: <%= %w(name country date_of_birth) %>
